// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulakguecdcfbsknsnser.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsYWtndWVjZGNmYnNrbnNuc2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTE2MTMsImV4cCI6MjA3MjY2NzYxM30.DpWWUXkbjv6zo-0s0ufqe3wc5X-rPJ4yLnyHALHDnyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});